[package]
name = "problog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
colorgrad = "0.6.2"
termcolor = "1.2.0"
